### ISSUE TITLE
what is the constant C?

### ISSUE THREAD

**Issue by gitunit** [bhyun-kim/NWD#2]
in the paper they mentioned supplementary materials to explain the constant C but unfortunately i was not able to find any material on that. do you know how i can determine C?

in the examples c=20, why?

**Comment by sbk1014** [comment]
As far as I remember, (because it's been a long time ago since I'd been working on this repo.) I was doing some experiments with different parameters. In the experimental result, the parameter C should be properly tuned for the dataset used. You can follow the paper's instruction or you can do some experiment to find the best one.

**Comment by gitunit** [comment]
i re-visted the paper and it says that they've used the "average absolute size of AI-TOD", i guess they mean the bbox size of longest dimension. and indeed it makes sense now
